## Data exploration and transformation

In [1]:
import pandas as pd

In [2]:
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

In [3]:
print("Training Data Overview:")
print(train_data.info())

Training Data Overview:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

In [4]:
print("Test Data Overview:")
print(test_data.info())

Test Data Overview:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB
None

In [5]:
train_data['Age'].fillna(-100, inplace=True)
test_data['Age'].fillna(-100, inplace=True)

In [6]:
bins = [-10,0, 12, 19, 64, 100] 
labels = ['NA','Child', 'Teenager', 'Adult', 'Senior']

In [7]:
train_data['Age_Category'] = pd.cut(train_data['Age'], bins=bins, labels=labels, right=True)
test_data['Age_Category'] = pd.cut(test_data['Age'], bins=bins, labels=labels, right=True)

In [8]:
train_data = pd.get_dummies(train_data, columns=['Age_Category'], drop_first=True)
test_data = pd.get_dummies(test_data, columns=['Age_Category'], drop_first=True)

In [9]:
print(test_data.info())
print(train_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   PassengerId            418 non-null    int64
 1   Pclass                 418 non-null    int64
 2   Name                   418 non-null    object
 3   Sex                    418 non-null    object
 4   Age                    418 non-null    float64
 5   SibSp                  418 non-null    int64
 6   Parch                  418 non-null    int64
 7   Ticket                 418 non-null    object
 8   Fare                   417 non-null    float64
 9   Cabin                  91 non-null     object
 10  Embarked               418 non-null    object
 11  Age_Category_Child     418 non-null    uint8
 12  Age_Category_Teenager  418 non-null    uint8
 13  Age_Category_Adult     418 non-null    uint8
 14  Age_Category_Senior    418 non-null    uint8
dtypes: float64(2), int64(4), object(5), uint8(4)
memory usage: 37.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   PassengerId            891 non-null    int64
 1   Survived               891 non-null    int64
 2   Pclass                 891 non-null    int64
 3   Name                   891 non-null    object
 4   Sex                    891 non-null    object
 5   Age                    891 non-null    float64
 6   SibSp                  891 non-null    int64
 7   Parch                  891 non-null    int64
 8   Ticket                 891 non-null    object
 9   Fare                   891 non-null    float64
 10  Cabin                  204 non-null    object
 11  Embarked               889 non-null    object
 12  Age_Category_Child     891 non-null    uint8
 13  Age_Category_Teenager  891 non-null    uint8
 14  Age_Category_Adult     891 non-null    uint8
 15  Age_Category_Senior    891 non-null    uint8
dtypes: float64(2), int64(5), object(5), uint8(4)
memory usage: 87.1+ KB
None

In [10]:
test_data['Fare'].fillna(test_data['Fare'].mean(), inplace=True)

In [11]:
train_data['Cabin_ind'] = train_data['Cabin'].apply(lambda x: 0 if pd.isna(x) else 1)
test_data['Cabin_ind'] = test_data['Cabin'].apply(lambda x: 0 if pd.isna(x) else 1)

In [12]:
train_data['Deck'] = train_data['Cabin'].apply(lambda x: str(x)[0] if pd.notna(x) else 'M')  # 'M' for Missing
test_data['Deck'] = test_data['Cabin'].apply(lambda x: str(x)[0] if pd.notna(x) else 'M')

In [13]:
train_data.drop('Cabin', axis=1, inplace=True)
test_data.drop('Cabin', axis=1, inplace=True)
print(test_data.info())
print(train_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   PassengerId            418 non-null    int64
 1   Pclass                 418 non-null    int64
 2   Name                   418 non-null    object
 3   Sex                    418 non-null    object
 4   Age                    418 non-null    float64
 5   SibSp                  418 non-null    int64
 6   Parch                  418 non-null    int64
 7   Ticket                 418 non-null    object
 8   Fare                   418 non-null    float64
 9   Embarked               418 non-null    object
 10  Age_Category_Child     418 non-null    uint8
 11  Age_Category_Teenager  418 non-null    uint8
 12  Age_Category_Adult     418 non-null    uint8
 13  Age_Category_Senior    418 non-null    uint8
 14  Cabin_ind              418 non-null    int64
 15  Deck                   418 non-null    object
dtypes: float64(2), int64(5), object(5), uint8(4)
memory usage: 40.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   PassengerId            891 non-null    int64
 1   Survived               891 non-null    int64
 2   Pclass                 891 non-null    int64
 3   Name                   891 non-null    object
 4   Sex                    891 non-null    object
 5   Age                    891 non-null    float64
 6   SibSp                  891 non-null    int64
 7   Parch                  891 non-null    int64
 8   Ticket                 891 non-null    object
 9   Fare                   891 non-null    float64
 10  Embarked               889 non-null    object
 11  Age_Category_Child     891 non-null    uint8
 12  Age_Category_Teenager  891 non-null    uint8
 13  Age_Category_Adult     891 non-null    uint8
 14  Age_Category_Senior    891 non-null    uint8
 15  Cabin_ind              891 non-null    int64
 16  Deck                   891 non-null    object
dtypes: float64(2), int64(6), object(5), uint8(4)
memory usage: 94.1+ KB
None

In [14]:
train_data = pd.get_dummies(train_data, columns=['Sex', 'Embarked', 'Deck'], drop_first=True, 
                            prefix={'Sex': 'Sex', 'Embarked': 'Embarked', 'Deck': 'Deck'})
test_data = pd.get_dummies(test_data, columns=['Sex', 'Embarked', 'Deck'], drop_first=True, 
                           prefix={'Sex': 'Sex', 'Embarked': 'Embarked', 'Deck': 'Deck'})

In [15]:
print(test_data['Ticket'])

0                  330911
1                  363272
2                  240276
3                  315154
4                 3101298
              ...
413             A.5. 3236
414              PC 17758
415    SOTON/O.Q. 3101262
416                359309
417                  2668
Name: Ticket, Length: 418, dtype: object

In [16]:
train_data['Ticket_prefix'] = train_data['Ticket'].apply(lambda x: str(x)[0:2])

In [17]:
test_data['Ticket_prefix'] = test_data['Ticket'].apply(lambda x: str(x)[0:2])

In [18]:
train_data = pd.get_dummies(train_data, columns=['Ticket_prefix'], drop_first=True)

In [19]:
test_data = pd.get_dummies(test_data, columns=['Ticket_prefix'], drop_first=True)

In [20]:
print(test_data.info())
print(train_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 69 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   PassengerId            418 non-null    int64
 1   Pclass                 418 non-null    int64
 2   Name                   418 non-null    object
 3   Age                    418 non-null    float64
 4   SibSp                  418 non-null    int64
 5   Parch                  418 non-null    int64
 6   Ticket                 418 non-null    object
 7   Fare                   418 non-null    float64
 8   Age_Category_Child     418 non-null    uint8
 9   Age_Category_Teenager  418 non-null    uint8
 10  Age_Category_Adult     418 non-null    uint8
 11  Age_Category_Senior    418 non-null    uint8
 12  Cabin_ind              418 non-null    int64
 13  Sex_male               418 non-null    uint8
 14  Embarked_Q             418 non-null    uint8
 15  Embarked_S             418 non-null    uint8
 16  Deck_B                 418 non-null    uint8
 17  Deck_C                 418 non-null    uint8
 18  Deck_D                 418 non-null    uint8
 19  Deck_E                 418 non-null    uint8
 20  Deck_F                 418 non-null    uint8
 21  Deck_G                 418 non-null    uint8
 22  Deck_M                 418 non-null    uint8
 23  Ticket_prefix_12       418 non-null    uint8
 24  Ticket_prefix_13       418 non-null    uint8
 25  Ticket_prefix_16       418 non-null    uint8
 26  Ticket_prefix_17       418 non-null    uint8
 27  Ticket_prefix_19       418 non-null    uint8
 28  Ticket_prefix_20       418 non-null    uint8
 29  Ticket_prefix_21       418 non-null    uint8
 30  Ticket_prefix_22       418 non-null    uint8
 31  Ticket_prefix_23       418 non-null    uint8
 32  Ticket_prefix_24       418 non-null    uint8
 33  Ticket_prefix_25       418 non-null    uint8
 34  Ticket_prefix_26       418 non-null    uint8
 35  Ticket_prefix_28       418 non-null    uint8
 36  Ticket_prefix_29       418 non-null    uint8
 37  Ticket_prefix_31       418 non-null    uint8
 38  Ticket_prefix_32       418 non-null    uint8
 39  Ticket_prefix_33       418 non-null    uint8
 40  Ticket_prefix_34       418 non-null    uint8
 41  Ticket_prefix_35       418 non-null    uint8
 42  Ticket_prefix_36       418 non-null    uint8
 43  Ticket_prefix_37       418 non-null    uint8
 44  Ticket_prefix_38       418 non-null    uint8
 45  Ticket_prefix_39       418 non-null    uint8
 46  Ticket_prefix_41       418 non-null    uint8
 47  Ticket_prefix_65       418 non-null    uint8
 48  Ticket_prefix_68       418 non-null    uint8
 49  Ticket_prefix_69       418 non-null    uint8
 50  Ticket_prefix_72       418 non-null    uint8
 51  Ticket_prefix_75       418 non-null    uint8
 52  Ticket_prefix_79       418 non-null    uint8
 53  Ticket_prefix_92       418 non-null    uint8
 54  Ticket_prefix_A.       418 non-null    uint8
 55  Ticket_prefix_A/       418 non-null    uint8
 56  Ticket_prefix_AQ       418 non-null    uint8
 57  Ticket_prefix_C        418 non-null    uint8
 58  Ticket_prefix_C.       418 non-null    uint8
 59  Ticket_prefix_CA       418 non-null    uint8
 60  Ticket_prefix_F.       418 non-null    uint8
 61  Ticket_prefix_LP       418 non-null    uint8
 62  Ticket_prefix_PC       418 non-null    uint8
 63  Ticket_prefix_PP       418 non-null    uint8
 64  Ticket_prefix_S.       418 non-null    uint8
 65  Ticket_prefix_SC       418 non-null    uint8
 66  Ticket_prefix_SO       418 non-null    uint8
 67  Ticket_prefix_ST       418 non-null    uint8
 68  Ticket_prefix_W.       418 non-null    uint8
dtypes: float64(2), int64(5), object(2), uint8(60)
memory usage: 54.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 80 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   PassengerId            891 non-null    int64
 1   Survived               891 non-null    int64
 2   Pclass                 891 non-null    int64
 3   Name                   891 non-null    object
 4   Age                    891 non-null    float64
 5   SibSp                  891 non-null    int64
 6   Parch                  891 non-null    int64
 7   Ticket                 891 non-null    object
 8   Fare                   891 non-null    float64
 9   Age_Category_Child     891 non-null    uint8
 10  Age_Category_Teenager  891 non-null    uint8
 11  Age_Category_Adult     891 non-null    uint8
 12  Age_Category_Senior    891 non-null    uint8
 13  Cabin_ind              891 non-null    int64
 14  Sex_male               891 non-null    uint8
 15  Embarked_Q             891 non-null    uint8
 16  Embarked_S             891 non-null    uint8
 17  Deck_B                 891 non-null    uint8
 18  Deck_C                 891 non-null    uint8
 19  Deck_D                 891 non-null    uint8
 20  Deck_E                 891 non-null    uint8
 21  Deck_F                 891 non-null    uint8
 22  Deck_G                 891 non-null    uint8
 23  Deck_M                 891 non-null    uint8
 24  Deck_T                 891 non-null    uint8
 25  Ticket_prefix_12       891 non-null    uint8
 26  Ticket_prefix_13       891 non-null    uint8
 27  Ticket_prefix_14       891 non-null    uint8
 28  Ticket_prefix_16       891 non-null    uint8
 29  Ticket_prefix_17       891 non-null    uint8
 30  Ticket_prefix_19       891 non-null    uint8
 31  Ticket_prefix_20       891 non-null    uint8
 32  Ticket_prefix_21       891 non-null    uint8
 33  Ticket_prefix_22       891 non-null    uint8
 34  Ticket_prefix_23       891 non-null    uint8
 35  Ticket_prefix_24       891 non-null    uint8
 36  Ticket_prefix_25       891 non-null    uint8
 37  Ticket_prefix_26       891 non-null    uint8
 38  Ticket_prefix_27       891 non-null    uint8
 39  Ticket_prefix_28       891 non-null    uint8
 40  Ticket_prefix_29       891 non-null    uint8
 41  Ticket_prefix_31       891 non-null    uint8
 42  Ticket_prefix_32       891 non-null    uint8
 43  Ticket_prefix_33       891 non-null    uint8
 44  Ticket_prefix_34       891 non-null    uint8
 45  Ticket_prefix_35       891 non-null    uint8
 46  Ticket_prefix_36       891 non-null    uint8
 47  Ticket_prefix_37       891 non-null    uint8
 48  Ticket_prefix_38       891 non-null    uint8
 49  Ticket_prefix_39       891 non-null    uint8
 50  Ticket_prefix_41       891 non-null    uint8
 51  Ticket_prefix_45       891 non-null    uint8
 52  Ticket_prefix_54       891 non-null    uint8
 53  Ticket_prefix_57       891 non-null    uint8
 54  Ticket_prefix_65       891 non-null    uint8
 55  Ticket_prefix_69       891 non-null    uint8
 56  Ticket_prefix_72       891 non-null    uint8
 57  Ticket_prefix_75       891 non-null    uint8
 58  Ticket_prefix_84       891 non-null    uint8
 59  Ticket_prefix_92       891 non-null    uint8
 60  Ticket_prefix_A.       891 non-null    uint8
 61  Ticket_prefix_A/       891 non-null    uint8
 62  Ticket_prefix_A4       891 non-null    uint8
 63  Ticket_prefix_C        891 non-null    uint8
 64  Ticket_prefix_C.       891 non-null    uint8
 65  Ticket_prefix_CA       891 non-null    uint8
 66  Ticket_prefix_F.       891 non-null    uint8
 67  Ticket_prefix_Fa       891 non-null    uint8
 68  Ticket_prefix_LI       891 non-null    uint8
 69  Ticket_prefix_P/       891 non-null    uint8
 70  Ticket_prefix_PC       891 non-null    uint8
 71  Ticket_prefix_PP       891 non-null    uint8
 72  Ticket_prefix_S.       891 non-null    uint8
 73  Ticket_prefix_SC       891 non-null    uint8
 74  Ticket_prefix_SO       891 non-null    uint8
 75  Ticket_prefix_ST       891 non-null    uint8
 76  Ticket_prefix_SW       891 non-null    uint8
 77  Ticket_prefix_W.       891 non-null    uint8
 78  Ticket_prefix_W/       891 non-null    uint8
 79  Ticket_prefix_WE       891 non-null    uint8
dtypes: float64(2), int64(6), object(2), uint8(70)
memory usage: 130.6+ KB
None

In [21]:
train_data.drop('Ticket', axis=1, inplace=True)
test_data.drop('Ticket', axis=1, inplace=True)

In [22]:
train_data.drop('Name', axis=1, inplace=True)
test_data.drop('Name', axis=1, inplace=True)

In [23]:
test_data

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Age_Category_Child,Age_Category_Teenager,Age_Category_Adult,Age_Category_Senior,...,Ticket_prefix_CA,Ticket_prefix_F.,Ticket_prefix_LP,Ticket_prefix_PC,Ticket_prefix_PP,Ticket_prefix_S.,Ticket_prefix_SC,Ticket_prefix_SO,Ticket_prefix_ST,Ticket_prefix_W.
0,892,3,34.5,0,0,7.8292,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,893,3,47.0,1,0,7.0000,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,894,2,62.0,0,0,9.6875,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,895,3,27.0,0,0,8.6625,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,896,3,22.0,1,1,12.2875,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,-100.0,0,0,8.0500,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
414,1306,1,39.0,0,0,108.9000,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
415,1307,3,38.5,0,0,7.2500,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
416,1308,3,-100.0,0,0,8.0500,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
417,1309,3,-100.0,1,1,22.3583,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
X_train = train_data.drop(['Survived', 'PassengerId'], axis=1)

In [25]:
y_train = train_data['Survived']

In [26]:
X_test = test_data.drop(['PassengerId'], axis=1)

In [27]:
train_columns = set(X_train.columns)
test_columns = set(X_test.columns)
missing_cols_test = train_columns - test_columns
for col in missing_cols_test:
    X_test[col] = 0
X_test = X_test[X_train.columns]

In [28]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 76 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Pclass                 418 non-null    int64
 1   Age                    418 non-null    float64
 2   SibSp                  418 non-null    int64
 3   Parch                  418 non-null    int64
 4   Fare                   418 non-null    float64
 5   Age_Category_Child     418 non-null    uint8
 6   Age_Category_Teenager  418 non-null    uint8
 7   Age_Category_Adult     418 non-null    uint8
 8   Age_Category_Senior    418 non-null    uint8
 9   Cabin_ind              418 non-null    int64
 10  Sex_male               418 non-null    uint8
 11  Embarked_Q             418 non-null    uint8
 12  Embarked_S             418 non-null    uint8
 13  Deck_B                 418 non-null    uint8
 14  Deck_C                 418 non-null    uint8
 15  Deck_D                 418 non-null    uint8
 16  Deck_E                 418 non-null    uint8
 17  Deck_F                 418 non-null    uint8
 18  Deck_G                 418 non-null    uint8
 19  Deck_M                 418 non-null    uint8
 20  Deck_T                 418 non-null    int64
 21  Ticket_prefix_12       418 non-null    uint8
 22  Ticket_prefix_13       418 non-null    uint8
 23  Ticket_prefix_14       418 non-null    int64
 24  Ticket_prefix_16       418 non-null    uint8
 25  Ticket_prefix_17       418 non-null    uint8
 26  Ticket_prefix_19       418 non-null    uint8
 27  Ticket_prefix_20       418 non-null    uint8
 28  Ticket_prefix_21       418 non-null    uint8
 29  Ticket_prefix_22       418 non-null    uint8
 30  Ticket_prefix_23       418 non-null    uint8
 31  Ticket_prefix_24       418 non-null    uint8
 32  Ticket_prefix_25       418 non-null    uint8
 33  Ticket_prefix_26       418 non-null    uint8
 34  Ticket_prefix_27       418 non-null    int64
 35  Ticket_prefix_28       418 non-null    uint8
 36  Ticket_prefix_29       418 non-null    uint8
 37  Ticket_prefix_31       418 non-null    uint8
 38  Ticket_prefix_32       418 non-null    uint8
 39  Ticket_prefix_33       418 non-null    uint8
 40  Ticket_prefix_34       418 non-null    uint8
 41  Ticket_prefix_35       418 non-null    uint8
 42  Ticket_prefix_36       418 non-null    uint8
 43  Ticket_prefix_37       418 non-null    uint8
 44  Ticket_prefix_38       418 non-null    uint8
 45  Ticket_prefix_39       418 non-null    uint8
 46  Ticket_prefix_41       418 non-null    uint8
 47  Ticket_prefix_45       418 non-null    int64
 48  Ticket_prefix_54       418 non-null    int64
 49  Ticket_prefix_57       418 non-null    int64
 50  Ticket_prefix_65       418 non-null    uint8
 51  Ticket_prefix_69       418 non-null    uint8
 52  Ticket_prefix_72       418 non-null    uint8
 53  Ticket_prefix_75       418 non-null    uint8
 54  Ticket_prefix_84       418 non-null    int64
 55  Ticket_prefix_92       418 non-null    uint8
 56  Ticket_prefix_A.       418 non-null    uint8
 57  Ticket_prefix_A/       418 non-null    uint8
 58  Ticket_prefix_A4       418 non-null    int64
 59  Ticket_prefix_C        418 non-null    uint8
 60  Ticket_prefix_C.       418 non-null    uint8
 61  Ticket_prefix_CA       418 non-null    uint8
 62  Ticket_prefix_F.       418 non-null    uint8
 63  Ticket_prefix_Fa       418 non-null    int64
 64  Ticket_prefix_LI       418 non-null    int64
 65  Ticket_prefix_P/       418 non-null    int64
 66  Ticket_prefix_PC       418 non-null    uint8
 67  Ticket_prefix_PP       418 non-null    uint8
 68  Ticket_prefix_S.       418 non-null    uint8
 69  Ticket_prefix_SC       418 non-null    uint8
 70  Ticket_prefix_SO       418 non-null    uint8
 71  Ticket_prefix_ST       418 non-null    uint8
 72  Ticket_prefix_SW       418 non-null    int64
 73  Ticket_prefix_W.       418 non-null    uint8
 74  Ticket_prefix_W/       418 non-null    int64
 75  Ticket_prefix_WE       418 non-null    int64
dtypes: float64(2), int64(18), uint8(56)
memory usage: 88.3 KB

In [29]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 76 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Pclass                 891 non-null    int64
 1   Age                    891 non-null    float64
 2   SibSp                  891 non-null    int64
 3   Parch                  891 non-null    int64
 4   Fare                   891 non-null    float64
 5   Age_Category_Child     891 non-null    uint8
 6   Age_Category_Teenager  891 non-null    uint8
 7   Age_Category_Adult     891 non-null    uint8
 8   Age_Category_Senior    891 non-null    uint8
 9   Cabin_ind              891 non-null    int64
 10  Sex_male               891 non-null    uint8
 11  Embarked_Q             891 non-null    uint8
 12  Embarked_S             891 non-null    uint8
 13  Deck_B                 891 non-null    uint8
 14  Deck_C                 891 non-null    uint8
 15  Deck_D                 891 non-null    uint8
 16  Deck_E                 891 non-null    uint8
 17  Deck_F                 891 non-null    uint8
 18  Deck_G                 891 non-null    uint8
 19  Deck_M                 891 non-null    uint8
 20  Deck_T                 891 non-null    uint8
 21  Ticket_prefix_12       891 non-null    uint8
 22  Ticket_prefix_13       891 non-null    uint8
 23  Ticket_prefix_14       891 non-null    uint8
 24  Ticket_prefix_16       891 non-null    uint8
 25  Ticket_prefix_17       891 non-null    uint8
 26  Ticket_prefix_19       891 non-null    uint8
 27  Ticket_prefix_20       891 non-null    uint8
 28  Ticket_prefix_21       891 non-null    uint8
 29  Ticket_prefix_22       891 non-null    uint8
 30  Ticket_prefix_23       891 non-null    uint8
 31  Ticket_prefix_24       891 non-null    uint8
 32  Ticket_prefix_25       891 non-null    uint8
 33  Ticket_prefix_26       891 non-null    uint8
 34  Ticket_prefix_27       891 non-null    uint8
 35  Ticket_prefix_28       891 non-null    uint8
 36  Ticket_prefix_29       891 non-null    uint8
 37  Ticket_prefix_31       891 non-null    uint8
 38  Ticket_prefix_32       891 non-null    uint8
 39  Ticket_prefix_33       891 non-null    uint8
 40  Ticket_prefix_34       891 non-null    uint8
 41  Ticket_prefix_35       891 non-null    uint8
 42  Ticket_prefix_36       891 non-null    uint8
 43  Ticket_prefix_37       891 non-null    uint8
 44  Ticket_prefix_38       891 non-null    uint8
 45  Ticket_prefix_39       891 non-null    uint8
 46  Ticket_prefix_41       891 non-null    uint8
 47  Ticket_prefix_45       891 non-null    uint8
 48  Ticket_prefix_54       891 non-null    uint8
 49  Ticket_prefix_57       891 non-null    uint8
 50  Ticket_prefix_65       891 non-null    uint8
 51  Ticket_prefix_69       891 non-null    uint8
 52  Ticket_prefix_72       891 non-null    uint8
 53  Ticket_prefix_75       891 non-null    uint8
 54  Ticket_prefix_84       891 non-null    uint8
 55  Ticket_prefix_92       891 non-null    uint8
 56  Ticket_prefix_A.       891 non-null    uint8
 57  Ticket_prefix_A/       891 non-null    uint8
 58  Ticket_prefix_A4       891 non-null    uint8
 59  Ticket_prefix_C        891 non-null    uint8
 60  Ticket_prefix_C.       891 non-null    uint8
 61  Ticket_prefix_CA       891 non-null    uint8
 62  Ticket_prefix_F.       891 non-null    uint8
 63  Ticket_prefix_Fa       891 non-null    uint8
 64  Ticket_prefix_LI       891 non-null    uint8
 65  Ticket_prefix_P/       891 non-null    uint8
 66  Ticket_prefix_PC       891 non-null    uint8
 67  Ticket_prefix_PP       891 non-null    uint8
 68  Ticket_prefix_S.       891 non-null    uint8
 69  Ticket_prefix_SC       891 non-null    uint8
 70  Ticket_prefix_SO       891 non-null    uint8
 71  Ticket_prefix_ST       891 non-null    uint8
 72  Ticket_prefix_SW       891 non-null    uint8
 73  Ticket_prefix_W.       891 non-null    uint8
 74  Ticket_prefix_W/       891 non-null    uint8
 75  Ticket_prefix_WE       891 non-null    uint8
dtypes: float64(2), int64(4), uint8(70)
memory usage: 102.8 KB

## Construct Decision Trees

In [36]:
import xgboost as xgb
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [37]:
X_train_split, X_val, y_train_split, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [49]:
param_grid = {
    'n_estimators': [30, 40, 50, 75, 100, 200],
    'max_depth': [5, 6,7, 8,9, 10,12,15],
    'learning_rate': [0.01,0.03, 0.1, 0.3],
    'subsample': [0.7,0.8, 0.9, 1.0],
    'colsample_bytree': [0.7,0.8, 0.9, 1.0]
}

grid_search = GridSearchCV(estimator=xgb.XGBClassifier(random_state=102), 
                           param_grid=param_grid, 
                           cv=5, 
                           n_jobs=-1, 
                           scoring='accuracy')

grid_search.fit(X_train_split, y_train_split)

print("Best parameters:", grid_search.best_params_)

results = grid_search.cv_results_

results_df = pd.DataFrame({
    'mean_test_score': results['mean_test_score'],
    'std_test_score': results['std_test_score'],
    'params': results['params'],
    'rank_test_score': results['rank_test_score']
})

print(results_df.sort_values(by='rank_test_score'))

Best parameters: {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 8, 'n_estimators': 75, 'subsample': 0.8}
      mean_test_score  std_test_score  \
277          0.844115        0.016751
860          0.844095        0.022010
45           0.844085        0.017587
301          0.842716        0.017940
2044         0.842716        0.012772
...               ...             ...
51           0.674165        0.008055
48           0.672767        0.008980
171          0.672767        0.006400
147          0.672767        0.006400
27           0.672757        0.009345

                                                 params  rank_test_score
277   {'colsample_bytree': 0.7, 'learning_rate': 0.0...                1
860   {'colsample_bytree': 0.8, 'learning_rate': 0.0...                2
45    {'colsample_bytree': 0.7, 'learning_rate': 0.0...                3
301   {'colsample_bytree': 0.7, 'learning_rate': 0.0...                4
2044  {'colsample_bytree': 0.9, 'learning_rate': 0.1...                4
...                                                 ...              ...
51    {'colsample_bytree': 0.7, 'learning_rate': 0.0...             3068
48    {'colsample_bytree': 0.7, 'learning_rate': 0.0...             3069
171   {'colsample_bytree': 0.7, 'learning_rate': 0.0...             3069
147   {'colsample_bytree': 0.7, 'learning_rate': 0.0...             3069
27    {'colsample_bytree': 0.7, 'learning_rate': 0.0...             3072

[3072 rows x 4 columns]

In [78]:
results_df.sort_values(by='rank_test_score').head(2)

,mean_test_score,std_test_score,params,rank_test_score
277,0.844115,0.016751,"{'colsample_bytree': 0.7, 'learning_rate': 0.0...",1
860,0.844095,0.022010,"{'colsample_bytree': 0.8, 'learning_rate': 0.0...",2

In [79]:
results_df.sort_values(by='rank_test_score').head(2)['params'].tolist()

[{'colsample_bytree': 0.7,
  'learning_rate': 0.03,
  'max_depth': 8,
  'n_estimators': 75,
  'subsample': 0.8},
 {'colsample_bytree': 0.8,
  'learning_rate': 0.01,
  'max_depth': 8,
  'n_estimators': 200,
  'subsample': 0.7}]

In [80]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier

base_models = [
    (f'xgb_model_{i}', XGBClassifier(**params, random_state=102))
    for i, params in enumerate(top_5_params)
]

In [81]:
meta_model = LogisticRegression()

In [82]:
from sklearn.ensemble import StackingClassifier

stacking_model = StackingClassifier(estimators=base_models, final_estimator=meta_model, cv=5)

stacking_model.fit(X_train_split, y_train_split)

accuracy = stacking_model.score(X_val, y_val)

In [83]:
accuracy

0.8324022346368715

Cross-Validation Scores: [0.8041958  0.82517483 0.86619718 0.77464789 0.80985915]
Mean CV Score: 0.8160149709445484

In [85]:
predictions = stacking_model.predict(X_test)

In [86]:
 results = pd.DataFrame({
     'PassengerId': test_data['PassengerId'],
     'Survived': predictions
    })

In [87]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 76 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Pclass                 891 non-null    int64
 1   Age                    891 non-null    float64
 2   SibSp                  891 non-null    int64
 3   Parch                  891 non-null    int64
 4   Fare                   891 non-null    float64
 5   Age_Category_Child     891 non-null    uint8
 6   Age_Category_Teenager  891 non-null    uint8
 7   Age_Category_Adult     891 non-null    uint8
 8   Age_Category_Senior    891 non-null    uint8
 9   Cabin_ind              891 non-null    int64
 10  Sex_male               891 non-null    uint8
 11  Embarked_Q             891 non-null    uint8
 12  Embarked_S             891 non-null    uint8
 13  Deck_B                 891 non-null    uint8
 14  Deck_C                 891 non-null    uint8
 15  Deck_D                 891 non-null    uint8
 16  Deck_E                 891 non-null    uint8
 17  Deck_F                 891 non-null    uint8
 18  Deck_G                 891 non-null    uint8
 19  Deck_M                 891 non-null    uint8
 20  Deck_T                 891 non-null    uint8
 21  Ticket_prefix_12       891 non-null    uint8
 22  Ticket_prefix_13       891 non-null    uint8
 23  Ticket_prefix_14       891 non-null    uint8
 24  Ticket_prefix_16       891 non-null    uint8
 25  Ticket_prefix_17       891 non-null    uint8
 26  Ticket_prefix_19       891 non-null    uint8
 27  Ticket_prefix_20       891 non-null    uint8
 28  Ticket_prefix_21       891 non-null    uint8
 29  Ticket_prefix_22       891 non-null    uint8
 30  Ticket_prefix_23       891 non-null    uint8
 31  Ticket_prefix_24       891 non-null    uint8
 32  Ticket_prefix_25       891 non-null    uint8
 33  Ticket_prefix_26       891 non-null    uint8
 34  Ticket_prefix_27       891 non-null    uint8
 35  Ticket_prefix_28       891 non-null    uint8
 36  Ticket_prefix_29       891 non-null    uint8
 37  Ticket_prefix_31       891 non-null    uint8
 38  Ticket_prefix_32       891 non-null    uint8
 39  Ticket_prefix_33       891 non-null    uint8
 40  Ticket_prefix_34       891 non-null    uint8
 41  Ticket_prefix_35       891 non-null    uint8
 42  Ticket_prefix_36       891 non-null    uint8
 43  Ticket_prefix_37       891 non-null    uint8
 44  Ticket_prefix_38       891 non-null    uint8
 45  Ticket_prefix_39       891 non-null    uint8
 46  Ticket_prefix_41       891 non-null    uint8
 47  Ticket_prefix_45       891 non-null    uint8
 48  Ticket_prefix_54       891 non-null    uint8
 49  Ticket_prefix_57       891 non-null    uint8
 50  Ticket_prefix_65       891 non-null    uint8
 51  Ticket_prefix_69       891 non-null    uint8
 52  Ticket_prefix_72       891 non-null    uint8
 53  Ticket_prefix_75       891 non-null    uint8
 54  Ticket_prefix_84       891 non-null    uint8
 55  Ticket_prefix_92       891 non-null    uint8
 56  Ticket_prefix_A.       891 non-null    uint8
 57  Ticket_prefix_A/       891 non-null    uint8
 58  Ticket_prefix_A4       891 non-null    uint8
 59  Ticket_prefix_C        891 non-null    uint8
 60  Ticket_prefix_C.       891 non-null    uint8
 61  Ticket_prefix_CA       891 non-null    uint8
 62  Ticket_prefix_F.       891 non-null    uint8
 63  Ticket_prefix_Fa       891 non-null    uint8
 64  Ticket_prefix_LI       891 non-null    uint8
 65  Ticket_prefix_P/       891 non-null    uint8
 66  Ticket_prefix_PC       891 non-null    uint8
 67  Ticket_prefix_PP       891 non-null    uint8
 68  Ticket_prefix_S.       891 non-null    uint8
 69  Ticket_prefix_SC       891 non-null    uint8
 70  Ticket_prefix_SO       891 non-null    uint8
 71  Ticket_prefix_ST       891 non-null    uint8
 72  Ticket_prefix_SW       891 non-null    uint8
 73  Ticket_prefix_W.       891 non-null    uint8
 74  Ticket_prefix_W/       891 non-null    uint8
 75  Ticket_prefix_WE       891 non-null    uint8
dtypes: float64(2), int64(4), uint8(70)
memory usage: 102.8 KB

In [88]:
output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('prediction.csv', index=False)